[package]
name = "langspec"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
env_logger = "0.11.8"
log = "0.4.28"
pingora = { version = "0.6.0", features = ["proxy"] }

[dev-dependencies]
tokio = { version = "1.47.1", features = ["full"] }
